//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICI_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SICIEntities : DbContext
    {
        public SICIEntities()
            : base("name=SICIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<SICI_spPatrimonio_Anualizado_Obtener_Result> SICI_spPatrimonio_Anualizado_Obtener(Nullable<int> iAño_Desde, Nullable<int> iAño_Hasta)
        {
            var iAño_DesdeParameter = iAño_Desde.HasValue ?
                new ObjectParameter("iAño_Desde", iAño_Desde) :
                new ObjectParameter("iAño_Desde", typeof(int));
    
            var iAño_HastaParameter = iAño_Hasta.HasValue ?
                new ObjectParameter("iAño_Hasta", iAño_Hasta) :
                new ObjectParameter("iAño_Hasta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SICI_spPatrimonio_Anualizado_Obtener_Result>("SICI_spPatrimonio_Anualizado_Obtener", iAño_DesdeParameter, iAño_HastaParameter);
        }
    
        public virtual ObjectResult<SICI_spPatrimonio_Total_Obtener_Result> SICI_spPatrimonio_Total_Obtener()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SICI_spPatrimonio_Total_Obtener_Result>("SICI_spPatrimonio_Total_Obtener");
        }
    
        public virtual ObjectResult<SICI_spPatrimonio_Anualizado_Obtener_FX_Result> SICI_spPatrimonio_Anualizado_Obtener_FX(Nullable<int> iAño_Desde, Nullable<int> iAño_Hasta)
        {
            var iAño_DesdeParameter = iAño_Desde.HasValue ?
                new ObjectParameter("iAño_Desde", iAño_Desde) :
                new ObjectParameter("iAño_Desde", typeof(int));
    
            var iAño_HastaParameter = iAño_Hasta.HasValue ?
                new ObjectParameter("iAño_Hasta", iAño_Hasta) :
                new ObjectParameter("iAño_Hasta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SICI_spPatrimonio_Anualizado_Obtener_FX_Result>("SICI_spPatrimonio_Anualizado_Obtener_FX", iAño_DesdeParameter, iAño_HastaParameter);
        }
    
        public virtual ObjectResult<SICI_spPatrimonio_Total_Obtener_FX_Result> SICI_spPatrimonio_Total_Obtener_FX()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SICI_spPatrimonio_Total_Obtener_FX_Result>("SICI_spPatrimonio_Total_Obtener_FX");
        }
    
        public virtual ObjectResult<SICI_spAltas_Inventario_Obtener_Result> SICI_spAltas_Inventario_Obtener(Nullable<int> iAño)
        {
            var iAñoParameter = iAño.HasValue ?
                new ObjectParameter("iAño", iAño) :
                new ObjectParameter("iAño", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SICI_spAltas_Inventario_Obtener_Result>("SICI_spAltas_Inventario_Obtener", iAñoParameter);
        }
    
        public virtual ObjectResult<SICI_spAltas_Inventario_Obtener_FX_Result> SICI_spAltas_Inventario_Obtener_FX(Nullable<int> iAño)
        {
            var iAñoParameter = iAño.HasValue ?
                new ObjectParameter("iAño", iAño) :
                new ObjectParameter("iAño", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SICI_spAltas_Inventario_Obtener_FX_Result>("SICI_spAltas_Inventario_Obtener_FX", iAñoParameter);
        }
    
        public virtual ObjectResult<SICI_spAmortizaciones_Inventario_Obtener_Result> SICI_spAmortizaciones_Inventario_Obtener(Nullable<int> iAño)
        {
            var iAñoParameter = iAño.HasValue ?
                new ObjectParameter("iAño", iAño) :
                new ObjectParameter("iAño", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SICI_spAmortizaciones_Inventario_Obtener_Result>("SICI_spAmortizaciones_Inventario_Obtener", iAñoParameter);
        }
    
        public virtual ObjectResult<SICI_spAmortizaciones_Inventario_Obtener_FX_Result> SICI_spAmortizaciones_Inventario_Obtener_FX(Nullable<int> iAño)
        {
            var iAñoParameter = iAño.HasValue ?
                new ObjectParameter("iAño", iAño) :
                new ObjectParameter("iAño", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SICI_spAmortizaciones_Inventario_Obtener_FX_Result>("SICI_spAmortizaciones_Inventario_Obtener_FX", iAñoParameter);
        }
    
        public virtual ObjectResult<SICI_spAmortizaciones_Detalladas_Obtener_Result> SICI_spAmortizaciones_Detalladas_Obtener(Nullable<int> iAño_Desde, Nullable<int> iAño_Hasta)
        {
            var iAño_DesdeParameter = iAño_Desde.HasValue ?
                new ObjectParameter("iAño_Desde", iAño_Desde) :
                new ObjectParameter("iAño_Desde", typeof(int));
    
            var iAño_HastaParameter = iAño_Hasta.HasValue ?
                new ObjectParameter("iAño_Hasta", iAño_Hasta) :
                new ObjectParameter("iAño_Hasta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SICI_spAmortizaciones_Detalladas_Obtener_Result>("SICI_spAmortizaciones_Detalladas_Obtener", iAño_DesdeParameter, iAño_HastaParameter);
        }
    
        public virtual ObjectResult<SICI_spInventario_Detallado_Obtener_Result> SICI_spInventario_Detallado_Obtener(Nullable<int> iAño)
        {
            var iAñoParameter = iAño.HasValue ?
                new ObjectParameter("iAño", iAño) :
                new ObjectParameter("iAño", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SICI_spInventario_Detallado_Obtener_Result>("SICI_spInventario_Detallado_Obtener", iAñoParameter);
        }
    
        public virtual ObjectResult<SICI_spBajas_Anualizadas_Obtener_Result> SICI_spBajas_Anualizadas_Obtener(Nullable<int> iAño_Desde, Nullable<int> iAño_Hasta)
        {
            var iAño_DesdeParameter = iAño_Desde.HasValue ?
                new ObjectParameter("iAño_Desde", iAño_Desde) :
                new ObjectParameter("iAño_Desde", typeof(int));
    
            var iAño_HastaParameter = iAño_Hasta.HasValue ?
                new ObjectParameter("iAño_Hasta", iAño_Hasta) :
                new ObjectParameter("iAño_Hasta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SICI_spBajas_Anualizadas_Obtener_Result>("SICI_spBajas_Anualizadas_Obtener", iAño_DesdeParameter, iAño_HastaParameter);
        }
    
        public virtual ObjectResult<SICI_spBajas_Inventario_Obtener_Result> SICI_spBajas_Inventario_Obtener(Nullable<int> iAño_Alta)
        {
            var iAño_AltaParameter = iAño_Alta.HasValue ?
                new ObjectParameter("iAño_Alta", iAño_Alta) :
                new ObjectParameter("iAño_Alta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SICI_spBajas_Inventario_Obtener_Result>("SICI_spBajas_Inventario_Obtener", iAño_AltaParameter);
        }
    }
}
