//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICI_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SIGMAEntities : DbContext
    {
        public SIGMAEntities()
            : base("name=SIGMAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<M18_OrigenGasto> M18_OrigenGasto { get; set; }
        public virtual DbSet<M18_Inventarios> M18_Inventarios { get; set; }
    
        public virtual ObjectResult<SIGMA_spPeliculas_Seleccionar_Result> SIGMA_spPeliculas_Seleccionar(string sCod_Pais, Nullable<int> iAño, Nullable<System.DateTime> dFecha_Desde, Nullable<System.DateTime> dFecha_Hasta)
        {
            var sCod_PaisParameter = sCod_Pais != null ?
                new ObjectParameter("sCod_Pais", sCod_Pais) :
                new ObjectParameter("sCod_Pais", typeof(string));
    
            var iAñoParameter = iAño.HasValue ?
                new ObjectParameter("iAño", iAño) :
                new ObjectParameter("iAño", typeof(int));
    
            var dFecha_DesdeParameter = dFecha_Desde.HasValue ?
                new ObjectParameter("dFecha_Desde", dFecha_Desde) :
                new ObjectParameter("dFecha_Desde", typeof(System.DateTime));
    
            var dFecha_HastaParameter = dFecha_Hasta.HasValue ?
                new ObjectParameter("dFecha_Hasta", dFecha_Hasta) :
                new ObjectParameter("dFecha_Hasta", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SIGMA_spPeliculas_Seleccionar_Result>("SIGMA_spPeliculas_Seleccionar", sCod_PaisParameter, iAñoParameter, dFecha_DesdeParameter, dFecha_HastaParameter);
        }
    
        public virtual ObjectResult<Pelicula> SIGMA_spPeliculas_Seleccionar_FX(string sCod_Pais, Nullable<int> iAño, Nullable<System.DateTime> dFecha_Desde, Nullable<System.DateTime> dFecha_Hasta)
        {
            var sCod_PaisParameter = sCod_Pais != null ?
                new ObjectParameter("sCod_Pais", sCod_Pais) :
                new ObjectParameter("sCod_Pais", typeof(string));
    
            var iAñoParameter = iAño.HasValue ?
                new ObjectParameter("iAño", iAño) :
                new ObjectParameter("iAño", typeof(int));
    
            var dFecha_DesdeParameter = dFecha_Desde.HasValue ?
                new ObjectParameter("dFecha_Desde", dFecha_Desde) :
                new ObjectParameter("dFecha_Desde", typeof(System.DateTime));
    
            var dFecha_HastaParameter = dFecha_Hasta.HasValue ?
                new ObjectParameter("dFecha_Hasta", dFecha_Hasta) :
                new ObjectParameter("dFecha_Hasta", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pelicula>("SIGMA_spPeliculas_Seleccionar_FX", sCod_PaisParameter, iAñoParameter, dFecha_DesdeParameter, dFecha_HastaParameter);
        }
    
        public virtual ObjectResult<SIGMA_spAltas_Anuales_Obtener_Result> SIGMA_spAltas_Anuales_Obtener(Nullable<int> iAño_Desde, Nullable<int> iAño_Hasta)
        {
            var iAño_DesdeParameter = iAño_Desde.HasValue ?
                new ObjectParameter("iAño_Desde", iAño_Desde) :
                new ObjectParameter("iAño_Desde", typeof(int));
    
            var iAño_HastaParameter = iAño_Hasta.HasValue ?
                new ObjectParameter("iAño_Hasta", iAño_Hasta) :
                new ObjectParameter("iAño_Hasta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SIGMA_spAltas_Anuales_Obtener_Result>("SIGMA_spAltas_Anuales_Obtener", iAño_DesdeParameter, iAño_HastaParameter);
        }
    
        public virtual ObjectResult<SIGMA_spAltas_Detalladas_Obtener_Result> SIGMA_spAltas_Detalladas_Obtener(string sNNE, Nullable<System.DateTime> dFecha_Desde, Nullable<System.DateTime> dFecha_Hasta)
        {
            var sNNEParameter = sNNE != null ?
                new ObjectParameter("sNNE", sNNE) :
                new ObjectParameter("sNNE", typeof(string));
    
            var dFecha_DesdeParameter = dFecha_Desde.HasValue ?
                new ObjectParameter("dFecha_Desde", dFecha_Desde) :
                new ObjectParameter("dFecha_Desde", typeof(System.DateTime));
    
            var dFecha_HastaParameter = dFecha_Hasta.HasValue ?
                new ObjectParameter("dFecha_Hasta", dFecha_Hasta) :
                new ObjectParameter("dFecha_Hasta", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SIGMA_spAltas_Detalladas_Obtener_Result>("SIGMA_spAltas_Detalladas_Obtener", sNNEParameter, dFecha_DesdeParameter, dFecha_HastaParameter);
        }
    
        public virtual ObjectResult<SIGMA_spAltas_Generales_Obtener_Result> SIGMA_spAltas_Generales_Obtener(Nullable<System.DateTime> dFecha_Desde, Nullable<System.DateTime> dFecha_Hasta, Nullable<int> iID_Origen)
        {
            var dFecha_DesdeParameter = dFecha_Desde.HasValue ?
                new ObjectParameter("dFecha_Desde", dFecha_Desde) :
                new ObjectParameter("dFecha_Desde", typeof(System.DateTime));
    
            var dFecha_HastaParameter = dFecha_Hasta.HasValue ?
                new ObjectParameter("dFecha_Hasta", dFecha_Hasta) :
                new ObjectParameter("dFecha_Hasta", typeof(System.DateTime));
    
            var iID_OrigenParameter = iID_Origen.HasValue ?
                new ObjectParameter("iID_Origen", iID_Origen) :
                new ObjectParameter("iID_Origen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SIGMA_spAltas_Generales_Obtener_Result>("SIGMA_spAltas_Generales_Obtener", dFecha_DesdeParameter, dFecha_HastaParameter, iID_OrigenParameter);
        }
    
        public virtual ObjectResult<SIGMA_spAltas_Totalizadas_Obtener_Result> SIGMA_spAltas_Totalizadas_Obtener(Nullable<int> iID_Inventario, Nullable<int> iAño_Desde, Nullable<int> iAño_Hasta)
        {
            var iID_InventarioParameter = iID_Inventario.HasValue ?
                new ObjectParameter("iID_Inventario", iID_Inventario) :
                new ObjectParameter("iID_Inventario", typeof(int));
    
            var iAño_DesdeParameter = iAño_Desde.HasValue ?
                new ObjectParameter("iAño_Desde", iAño_Desde) :
                new ObjectParameter("iAño_Desde", typeof(int));
    
            var iAño_HastaParameter = iAño_Hasta.HasValue ?
                new ObjectParameter("iAño_Hasta", iAño_Hasta) :
                new ObjectParameter("iAño_Hasta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SIGMA_spAltas_Totalizadas_Obtener_Result>("SIGMA_spAltas_Totalizadas_Obtener", iID_InventarioParameter, iAño_DesdeParameter, iAño_HastaParameter);
        }
    
        public virtual ObjectResult<SIGMA_spAmortizaciones_Anuales_Obtener_Result> SIGMA_spAmortizaciones_Anuales_Obtener(Nullable<System.DateTime> dFecha_Desde, Nullable<System.DateTime> dFecha_Hasta, string sNroLote, string sNNE)
        {
            var dFecha_DesdeParameter = dFecha_Desde.HasValue ?
                new ObjectParameter("dFecha_Desde", dFecha_Desde) :
                new ObjectParameter("dFecha_Desde", typeof(System.DateTime));
    
            var dFecha_HastaParameter = dFecha_Hasta.HasValue ?
                new ObjectParameter("dFecha_Hasta", dFecha_Hasta) :
                new ObjectParameter("dFecha_Hasta", typeof(System.DateTime));
    
            var sNroLoteParameter = sNroLote != null ?
                new ObjectParameter("sNroLote", sNroLote) :
                new ObjectParameter("sNroLote", typeof(string));
    
            var sNNEParameter = sNNE != null ?
                new ObjectParameter("sNNE", sNNE) :
                new ObjectParameter("sNNE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SIGMA_spAmortizaciones_Anuales_Obtener_Result>("SIGMA_spAmortizaciones_Anuales_Obtener", dFecha_DesdeParameter, dFecha_HastaParameter, sNroLoteParameter, sNNEParameter);
        }
    
        public virtual ObjectResult<SIGMA_spDescargos_Valorizados_Obtener_Result> SIGMA_spDescargos_Valorizados_Obtener(Nullable<System.DateTime> dFecha_Desde, Nullable<System.DateTime> dFecha_Hasta, string sSigla, string sNNE)
        {
            var dFecha_DesdeParameter = dFecha_Desde.HasValue ?
                new ObjectParameter("dFecha_Desde", dFecha_Desde) :
                new ObjectParameter("dFecha_Desde", typeof(System.DateTime));
    
            var dFecha_HastaParameter = dFecha_Hasta.HasValue ?
                new ObjectParameter("dFecha_Hasta", dFecha_Hasta) :
                new ObjectParameter("dFecha_Hasta", typeof(System.DateTime));
    
            var sSiglaParameter = sSigla != null ?
                new ObjectParameter("sSigla", sSigla) :
                new ObjectParameter("sSigla", typeof(string));
    
            var sNNEParameter = sNNE != null ?
                new ObjectParameter("sNNE", sNNE) :
                new ObjectParameter("sNNE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SIGMA_spDescargos_Valorizados_Obtener_Result>("SIGMA_spDescargos_Valorizados_Obtener", dFecha_DesdeParameter, dFecha_HastaParameter, sSiglaParameter, sNNEParameter);
        }
    
        public virtual ObjectResult<SIGMA_spDespiece_Valorizado_Obtener_Result> SIGMA_spDespiece_Valorizado_Obtener(string sNNE_Primario, Nullable<long> iNroInven_Primario, string sNroSerie_Primario)
        {
            var sNNE_PrimarioParameter = sNNE_Primario != null ?
                new ObjectParameter("sNNE_Primario", sNNE_Primario) :
                new ObjectParameter("sNNE_Primario", typeof(string));
    
            var iNroInven_PrimarioParameter = iNroInven_Primario.HasValue ?
                new ObjectParameter("iNroInven_Primario", iNroInven_Primario) :
                new ObjectParameter("iNroInven_Primario", typeof(long));
    
            var sNroSerie_PrimarioParameter = sNroSerie_Primario != null ?
                new ObjectParameter("sNroSerie_Primario", sNroSerie_Primario) :
                new ObjectParameter("sNroSerie_Primario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SIGMA_spDespiece_Valorizado_Obtener_Result>("SIGMA_spDespiece_Valorizado_Obtener", sNNE_PrimarioParameter, iNroInven_PrimarioParameter, sNroSerie_PrimarioParameter);
        }
    
        public virtual ObjectResult<SIGMA_spEfectos_Amortizados_Obtener_Result> SIGMA_spEfectos_Amortizados_Obtener(Nullable<System.DateTime> dFecha_Desde, Nullable<System.DateTime> dFecha_Hasta)
        {
            var dFecha_DesdeParameter = dFecha_Desde.HasValue ?
                new ObjectParameter("dFecha_Desde", dFecha_Desde) :
                new ObjectParameter("dFecha_Desde", typeof(System.DateTime));
    
            var dFecha_HastaParameter = dFecha_Hasta.HasValue ?
                new ObjectParameter("dFecha_Hasta", dFecha_Hasta) :
                new ObjectParameter("dFecha_Hasta", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SIGMA_spEfectos_Amortizados_Obtener_Result>("SIGMA_spEfectos_Amortizados_Obtener", dFecha_DesdeParameter, dFecha_HastaParameter);
        }
    
        public virtual ObjectResult<SIGMA_spInventario_Valorizado_Obtener_Result> SIGMA_spInventario_Valorizado_Obtener(Nullable<int> iID_Inventario, Nullable<int> iAño)
        {
            var iID_InventarioParameter = iID_Inventario.HasValue ?
                new ObjectParameter("iID_Inventario", iID_Inventario) :
                new ObjectParameter("iID_Inventario", typeof(int));
    
            var iAñoParameter = iAño.HasValue ?
                new ObjectParameter("iAño", iAño) :
                new ObjectParameter("iAño", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SIGMA_spInventario_Valorizado_Obtener_Result>("SIGMA_spInventario_Valorizado_Obtener", iID_InventarioParameter, iAñoParameter);
        }
    
        public virtual ObjectResult<SIGMA_spLotes_Destino_Obtener_Result> SIGMA_spLotes_Destino_Obtener(Nullable<System.DateTime> dFecha_Desde, Nullable<System.DateTime> dFecha_Hasta, string sSigla)
        {
            var dFecha_DesdeParameter = dFecha_Desde.HasValue ?
                new ObjectParameter("dFecha_Desde", dFecha_Desde) :
                new ObjectParameter("dFecha_Desde", typeof(System.DateTime));
    
            var dFecha_HastaParameter = dFecha_Hasta.HasValue ?
                new ObjectParameter("dFecha_Hasta", dFecha_Hasta) :
                new ObjectParameter("dFecha_Hasta", typeof(System.DateTime));
    
            var sSiglaParameter = sSigla != null ?
                new ObjectParameter("sSigla", sSigla) :
                new ObjectParameter("sSigla", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SIGMA_spLotes_Destino_Obtener_Result>("SIGMA_spLotes_Destino_Obtener", dFecha_DesdeParameter, dFecha_HastaParameter, sSiglaParameter);
        }
    
        public virtual ObjectResult<SIGMA_spLotes_Inventario_Obtener_Result> SIGMA_spLotes_Inventario_Obtener(Nullable<System.DateTime> dFecha_Desde, Nullable<System.DateTime> dFecha_Hasta, Nullable<int> iID_Inventario)
        {
            var dFecha_DesdeParameter = dFecha_Desde.HasValue ?
                new ObjectParameter("dFecha_Desde", dFecha_Desde) :
                new ObjectParameter("dFecha_Desde", typeof(System.DateTime));
    
            var dFecha_HastaParameter = dFecha_Hasta.HasValue ?
                new ObjectParameter("dFecha_Hasta", dFecha_Hasta) :
                new ObjectParameter("dFecha_Hasta", typeof(System.DateTime));
    
            var iID_InventarioParameter = iID_Inventario.HasValue ?
                new ObjectParameter("iID_Inventario", iID_Inventario) :
                new ObjectParameter("iID_Inventario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SIGMA_spLotes_Inventario_Obtener_Result>("SIGMA_spLotes_Inventario_Obtener", dFecha_DesdeParameter, dFecha_HastaParameter, iID_InventarioParameter);
        }
    
        public virtual ObjectResult<SIGMA_spTotales_Cargo_Destino_Obtener_Result> SIGMA_spTotales_Cargo_Destino_Obtener(string sSigla, string sCargo_Destino)
        {
            var sSiglaParameter = sSigla != null ?
                new ObjectParameter("sSigla", sSigla) :
                new ObjectParameter("sSigla", typeof(string));
    
            var sCargo_DestinoParameter = sCargo_Destino != null ?
                new ObjectParameter("sCargo_Destino", sCargo_Destino) :
                new ObjectParameter("sCargo_Destino", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SIGMA_spTotales_Cargo_Destino_Obtener_Result>("SIGMA_spTotales_Cargo_Destino_Obtener", sSiglaParameter, sCargo_DestinoParameter);
        }
    
        public virtual ObjectResult<SIGMA_spTotales_Cargo_Efecto_Obtener_Result> SIGMA_spTotales_Cargo_Efecto_Obtener(string sCod_Cargo_Efecto, string sSigla_Destino, string sCod_CargoDestino)
        {
            var sCod_Cargo_EfectoParameter = sCod_Cargo_Efecto != null ?
                new ObjectParameter("sCod_Cargo_Efecto", sCod_Cargo_Efecto) :
                new ObjectParameter("sCod_Cargo_Efecto", typeof(string));
    
            var sSigla_DestinoParameter = sSigla_Destino != null ?
                new ObjectParameter("sSigla_Destino", sSigla_Destino) :
                new ObjectParameter("sSigla_Destino", typeof(string));
    
            var sCod_CargoDestinoParameter = sCod_CargoDestino != null ?
                new ObjectParameter("sCod_CargoDestino", sCod_CargoDestino) :
                new ObjectParameter("sCod_CargoDestino", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SIGMA_spTotales_Cargo_Efecto_Obtener_Result>("SIGMA_spTotales_Cargo_Efecto_Obtener", sCod_Cargo_EfectoParameter, sSigla_DestinoParameter, sCod_CargoDestinoParameter);
        }
    
        public virtual ObjectResult<SIGMA_spTotales_Destino_Obtener_Result> SIGMA_spTotales_Destino_Obtener(string sZona, string sSigla)
        {
            var sZonaParameter = sZona != null ?
                new ObjectParameter("sZona", sZona) :
                new ObjectParameter("sZona", typeof(string));
    
            var sSiglaParameter = sSigla != null ?
                new ObjectParameter("sSigla", sSigla) :
                new ObjectParameter("sSigla", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SIGMA_spTotales_Destino_Obtener_Result>("SIGMA_spTotales_Destino_Obtener", sZonaParameter, sSiglaParameter);
        }
    
        public virtual ObjectResult<SIGMA_spTotales_Efecto_Obtener_Result> SIGMA_spTotales_Efecto_Obtener(string sNNE, string sSigla_Destino, string sCod_CargoDestino, string sCargo_Efecto)
        {
            var sNNEParameter = sNNE != null ?
                new ObjectParameter("sNNE", sNNE) :
                new ObjectParameter("sNNE", typeof(string));
    
            var sSigla_DestinoParameter = sSigla_Destino != null ?
                new ObjectParameter("sSigla_Destino", sSigla_Destino) :
                new ObjectParameter("sSigla_Destino", typeof(string));
    
            var sCod_CargoDestinoParameter = sCod_CargoDestino != null ?
                new ObjectParameter("sCod_CargoDestino", sCod_CargoDestino) :
                new ObjectParameter("sCod_CargoDestino", typeof(string));
    
            var sCargo_EfectoParameter = sCargo_Efecto != null ?
                new ObjectParameter("sCargo_Efecto", sCargo_Efecto) :
                new ObjectParameter("sCargo_Efecto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SIGMA_spTotales_Efecto_Obtener_Result>("SIGMA_spTotales_Efecto_Obtener", sNNEParameter, sSigla_DestinoParameter, sCod_CargoDestinoParameter, sCargo_EfectoParameter);
        }
    
        public virtual ObjectResult<SIGMA_spValorizacion_Detallada_Obtener_Result> SIGMA_spValorizacion_Detallada_Obtener(string sNNE, string sNroLote, string sSigla)
        {
            var sNNEParameter = sNNE != null ?
                new ObjectParameter("sNNE", sNNE) :
                new ObjectParameter("sNNE", typeof(string));
    
            var sNroLoteParameter = sNroLote != null ?
                new ObjectParameter("sNroLote", sNroLote) :
                new ObjectParameter("sNroLote", typeof(string));
    
            var sSiglaParameter = sSigla != null ?
                new ObjectParameter("sSigla", sSigla) :
                new ObjectParameter("sSigla", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SIGMA_spValorizacion_Detallada_Obtener_Result>("SIGMA_spValorizacion_Detallada_Obtener", sNNEParameter, sNroLoteParameter, sSiglaParameter);
        }
    
        public virtual ObjectResult<SIGMA_spAltas_Anuales_Obtener_Result> SIGMA_spAltas_Anuales_Obtener_FX(Nullable<int> iAño_Desde, Nullable<int> iAño_Hasta)
        {
            var iAño_DesdeParameter = iAño_Desde.HasValue ?
                new ObjectParameter("iAño_Desde", iAño_Desde) :
                new ObjectParameter("iAño_Desde", typeof(int));
    
            var iAño_HastaParameter = iAño_Hasta.HasValue ?
                new ObjectParameter("iAño_Hasta", iAño_Hasta) :
                new ObjectParameter("iAño_Hasta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SIGMA_spAltas_Anuales_Obtener_Result>("SIGMA_spAltas_Anuales_Obtener_FX", iAño_DesdeParameter, iAño_HastaParameter);
        }
    
        public virtual ObjectResult<SIGMA_spAltas_Detalladas_Obtener_Result> SIGMA_spAltas_Detalladas_Obtener_FX(string sNNE, Nullable<System.DateTime> dFecha_Desde, Nullable<System.DateTime> dFecha_Hasta)
        {
            var sNNEParameter = sNNE != null ?
                new ObjectParameter("sNNE", sNNE) :
                new ObjectParameter("sNNE", typeof(string));
    
            var dFecha_DesdeParameter = dFecha_Desde.HasValue ?
                new ObjectParameter("dFecha_Desde", dFecha_Desde) :
                new ObjectParameter("dFecha_Desde", typeof(System.DateTime));
    
            var dFecha_HastaParameter = dFecha_Hasta.HasValue ?
                new ObjectParameter("dFecha_Hasta", dFecha_Hasta) :
                new ObjectParameter("dFecha_Hasta", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SIGMA_spAltas_Detalladas_Obtener_Result>("SIGMA_spAltas_Detalladas_Obtener_FX", sNNEParameter, dFecha_DesdeParameter, dFecha_HastaParameter);
        }
    
        public virtual ObjectResult<SIGMA_spAltas_Generales_Obtener_Result> SIGMA_spAltas_Generales_Obtener_FX(Nullable<System.DateTime> dFecha_Desde, Nullable<System.DateTime> dFecha_Hasta, Nullable<int> iID_Origen)
        {
            var dFecha_DesdeParameter = dFecha_Desde.HasValue ?
                new ObjectParameter("dFecha_Desde", dFecha_Desde) :
                new ObjectParameter("dFecha_Desde", typeof(System.DateTime));
    
            var dFecha_HastaParameter = dFecha_Hasta.HasValue ?
                new ObjectParameter("dFecha_Hasta", dFecha_Hasta) :
                new ObjectParameter("dFecha_Hasta", typeof(System.DateTime));
    
            var iID_OrigenParameter = iID_Origen.HasValue ?
                new ObjectParameter("iID_Origen", iID_Origen) :
                new ObjectParameter("iID_Origen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SIGMA_spAltas_Generales_Obtener_Result>("SIGMA_spAltas_Generales_Obtener_FX", dFecha_DesdeParameter, dFecha_HastaParameter, iID_OrigenParameter);
        }
    
        public virtual ObjectResult<SIGMA_spAltas_Totalizadas_Obtener_Result> SIGMA_spAltas_Totalizadas_Obtener_FX(Nullable<int> iID_Inventario, Nullable<int> iAño_Desde, Nullable<int> iAño_Hasta)
        {
            var iID_InventarioParameter = iID_Inventario.HasValue ?
                new ObjectParameter("iID_Inventario", iID_Inventario) :
                new ObjectParameter("iID_Inventario", typeof(int));
    
            var iAño_DesdeParameter = iAño_Desde.HasValue ?
                new ObjectParameter("iAño_Desde", iAño_Desde) :
                new ObjectParameter("iAño_Desde", typeof(int));
    
            var iAño_HastaParameter = iAño_Hasta.HasValue ?
                new ObjectParameter("iAño_Hasta", iAño_Hasta) :
                new ObjectParameter("iAño_Hasta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SIGMA_spAltas_Totalizadas_Obtener_Result>("SIGMA_spAltas_Totalizadas_Obtener_FX", iID_InventarioParameter, iAño_DesdeParameter, iAño_HastaParameter);
        }
    
        public virtual ObjectResult<SIGMA_spAmortizaciones_Anuales_Obtener_Result> SIGMA_spAmortizaciones_Anuales_Obtener_FX(Nullable<System.DateTime> dFecha_Desde, Nullable<System.DateTime> dFecha_Hasta, string sNroLote, string sNNE)
        {
            var dFecha_DesdeParameter = dFecha_Desde.HasValue ?
                new ObjectParameter("dFecha_Desde", dFecha_Desde) :
                new ObjectParameter("dFecha_Desde", typeof(System.DateTime));
    
            var dFecha_HastaParameter = dFecha_Hasta.HasValue ?
                new ObjectParameter("dFecha_Hasta", dFecha_Hasta) :
                new ObjectParameter("dFecha_Hasta", typeof(System.DateTime));
    
            var sNroLoteParameter = sNroLote != null ?
                new ObjectParameter("sNroLote", sNroLote) :
                new ObjectParameter("sNroLote", typeof(string));
    
            var sNNEParameter = sNNE != null ?
                new ObjectParameter("sNNE", sNNE) :
                new ObjectParameter("sNNE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SIGMA_spAmortizaciones_Anuales_Obtener_Result>("SIGMA_spAmortizaciones_Anuales_Obtener_FX", dFecha_DesdeParameter, dFecha_HastaParameter, sNroLoteParameter, sNNEParameter);
        }
    
        public virtual ObjectResult<SIGMA_spDescargos_Valorizados_Obtener_Result> SIGMA_spDescargos_Valorizados_Obtener_FX(Nullable<System.DateTime> dFecha_Desde, Nullable<System.DateTime> dFecha_Hasta, string sSigla, string sNNE)
        {
            var dFecha_DesdeParameter = dFecha_Desde.HasValue ?
                new ObjectParameter("dFecha_Desde", dFecha_Desde) :
                new ObjectParameter("dFecha_Desde", typeof(System.DateTime));
    
            var dFecha_HastaParameter = dFecha_Hasta.HasValue ?
                new ObjectParameter("dFecha_Hasta", dFecha_Hasta) :
                new ObjectParameter("dFecha_Hasta", typeof(System.DateTime));
    
            var sSiglaParameter = sSigla != null ?
                new ObjectParameter("sSigla", sSigla) :
                new ObjectParameter("sSigla", typeof(string));
    
            var sNNEParameter = sNNE != null ?
                new ObjectParameter("sNNE", sNNE) :
                new ObjectParameter("sNNE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SIGMA_spDescargos_Valorizados_Obtener_Result>("SIGMA_spDescargos_Valorizados_Obtener_FX", dFecha_DesdeParameter, dFecha_HastaParameter, sSiglaParameter, sNNEParameter);
        }
    
        public virtual ObjectResult<SIGMA_spDespiece_Valorizado_Obtener_Result> SIGMA_spDespiece_Valorizado_Obtener_FX(string sNNE_Primario, Nullable<long> iNroInven_Primario, string sNroSerie_Primario)
        {
            var sNNE_PrimarioParameter = sNNE_Primario != null ?
                new ObjectParameter("sNNE_Primario", sNNE_Primario) :
                new ObjectParameter("sNNE_Primario", typeof(string));
    
            var iNroInven_PrimarioParameter = iNroInven_Primario.HasValue ?
                new ObjectParameter("iNroInven_Primario", iNroInven_Primario) :
                new ObjectParameter("iNroInven_Primario", typeof(long));
    
            var sNroSerie_PrimarioParameter = sNroSerie_Primario != null ?
                new ObjectParameter("sNroSerie_Primario", sNroSerie_Primario) :
                new ObjectParameter("sNroSerie_Primario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SIGMA_spDespiece_Valorizado_Obtener_Result>("SIGMA_spDespiece_Valorizado_Obtener_FX", sNNE_PrimarioParameter, iNroInven_PrimarioParameter, sNroSerie_PrimarioParameter);
        }
    
        public virtual ObjectResult<SIGMA_spEfectos_Amortizados_Obtener_Result> SIGMA_spEfectos_Amortizados_Obtener_FX(Nullable<System.DateTime> dFecha_Desde, Nullable<System.DateTime> dFecha_Hasta)
        {
            var dFecha_DesdeParameter = dFecha_Desde.HasValue ?
                new ObjectParameter("dFecha_Desde", dFecha_Desde) :
                new ObjectParameter("dFecha_Desde", typeof(System.DateTime));
    
            var dFecha_HastaParameter = dFecha_Hasta.HasValue ?
                new ObjectParameter("dFecha_Hasta", dFecha_Hasta) :
                new ObjectParameter("dFecha_Hasta", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SIGMA_spEfectos_Amortizados_Obtener_Result>("SIGMA_spEfectos_Amortizados_Obtener_FX", dFecha_DesdeParameter, dFecha_HastaParameter);
        }
    
        public virtual ObjectResult<SIGMA_spInventario_Valorizado_Obtener_Result> SIGMA_spInventario_Valorizado_Obtener_FX(Nullable<int> iID_Inventario, Nullable<int> iAño)
        {
            var iID_InventarioParameter = iID_Inventario.HasValue ?
                new ObjectParameter("iID_Inventario", iID_Inventario) :
                new ObjectParameter("iID_Inventario", typeof(int));
    
            var iAñoParameter = iAño.HasValue ?
                new ObjectParameter("iAño", iAño) :
                new ObjectParameter("iAño", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SIGMA_spInventario_Valorizado_Obtener_Result>("SIGMA_spInventario_Valorizado_Obtener_FX", iID_InventarioParameter, iAñoParameter);
        }
    
        public virtual ObjectResult<SIGMA_spLotes_Destino_Obtener_Result> SIGMA_spLotes_Destino_Obtener_FX(Nullable<System.DateTime> dFecha_Desde, Nullable<System.DateTime> dFecha_Hasta, string sSigla)
        {
            var dFecha_DesdeParameter = dFecha_Desde.HasValue ?
                new ObjectParameter("dFecha_Desde", dFecha_Desde) :
                new ObjectParameter("dFecha_Desde", typeof(System.DateTime));
    
            var dFecha_HastaParameter = dFecha_Hasta.HasValue ?
                new ObjectParameter("dFecha_Hasta", dFecha_Hasta) :
                new ObjectParameter("dFecha_Hasta", typeof(System.DateTime));
    
            var sSiglaParameter = sSigla != null ?
                new ObjectParameter("sSigla", sSigla) :
                new ObjectParameter("sSigla", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SIGMA_spLotes_Destino_Obtener_Result>("SIGMA_spLotes_Destino_Obtener_FX", dFecha_DesdeParameter, dFecha_HastaParameter, sSiglaParameter);
        }
    
        public virtual ObjectResult<SIGMA_spLotes_Inventario_Obtener_Result> SIGMA_spLotes_Inventario_Obtener_FX(Nullable<System.DateTime> dFecha_Desde, Nullable<System.DateTime> dFecha_Hasta, Nullable<int> iID_Inventario)
        {
            var dFecha_DesdeParameter = dFecha_Desde.HasValue ?
                new ObjectParameter("dFecha_Desde", dFecha_Desde) :
                new ObjectParameter("dFecha_Desde", typeof(System.DateTime));
    
            var dFecha_HastaParameter = dFecha_Hasta.HasValue ?
                new ObjectParameter("dFecha_Hasta", dFecha_Hasta) :
                new ObjectParameter("dFecha_Hasta", typeof(System.DateTime));
    
            var iID_InventarioParameter = iID_Inventario.HasValue ?
                new ObjectParameter("iID_Inventario", iID_Inventario) :
                new ObjectParameter("iID_Inventario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SIGMA_spLotes_Inventario_Obtener_Result>("SIGMA_spLotes_Inventario_Obtener_FX", dFecha_DesdeParameter, dFecha_HastaParameter, iID_InventarioParameter);
        }
    
        public virtual ObjectResult<SIGMA_spTotales_Cargo_Destino_Obtener_Result> SIGMA_spTotales_Cargo_Destino_Obtener_FX(string sSigla, string sCargo_Destino)
        {
            var sSiglaParameter = sSigla != null ?
                new ObjectParameter("sSigla", sSigla) :
                new ObjectParameter("sSigla", typeof(string));
    
            var sCargo_DestinoParameter = sCargo_Destino != null ?
                new ObjectParameter("sCargo_Destino", sCargo_Destino) :
                new ObjectParameter("sCargo_Destino", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SIGMA_spTotales_Cargo_Destino_Obtener_Result>("SIGMA_spTotales_Cargo_Destino_Obtener_FX", sSiglaParameter, sCargo_DestinoParameter);
        }
    
        public virtual ObjectResult<SIGMA_spTotales_Cargo_Efecto_Obtener_Result> SIGMA_spTotales_Cargo_Efecto_Obtener_FX(string sCod_Cargo_Efecto, string sSigla_Destino, string sCod_CargoDestino)
        {
            var sCod_Cargo_EfectoParameter = sCod_Cargo_Efecto != null ?
                new ObjectParameter("sCod_Cargo_Efecto", sCod_Cargo_Efecto) :
                new ObjectParameter("sCod_Cargo_Efecto", typeof(string));
    
            var sSigla_DestinoParameter = sSigla_Destino != null ?
                new ObjectParameter("sSigla_Destino", sSigla_Destino) :
                new ObjectParameter("sSigla_Destino", typeof(string));
    
            var sCod_CargoDestinoParameter = sCod_CargoDestino != null ?
                new ObjectParameter("sCod_CargoDestino", sCod_CargoDestino) :
                new ObjectParameter("sCod_CargoDestino", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SIGMA_spTotales_Cargo_Efecto_Obtener_Result>("SIGMA_spTotales_Cargo_Efecto_Obtener_FX", sCod_Cargo_EfectoParameter, sSigla_DestinoParameter, sCod_CargoDestinoParameter);
        }
    
        public virtual ObjectResult<SIGMA_spTotales_Destino_Obtener_Result> SIGMA_spTotales_Destino_Obtener_FX(string sZona, string sSigla)
        {
            var sZonaParameter = sZona != null ?
                new ObjectParameter("sZona", sZona) :
                new ObjectParameter("sZona", typeof(string));
    
            var sSiglaParameter = sSigla != null ?
                new ObjectParameter("sSigla", sSigla) :
                new ObjectParameter("sSigla", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SIGMA_spTotales_Destino_Obtener_Result>("SIGMA_spTotales_Destino_Obtener_FX", sZonaParameter, sSiglaParameter);
        }
    
        public virtual ObjectResult<SIGMA_spTotales_Efecto_Obtener_Result> SIGMA_spTotales_Efecto_Obtener_FX(string sNNE, string sSigla_Destino, string sCod_CargoDestino, string sCargo_Efecto)
        {
            var sNNEParameter = sNNE != null ?
                new ObjectParameter("sNNE", sNNE) :
                new ObjectParameter("sNNE", typeof(string));
    
            var sSigla_DestinoParameter = sSigla_Destino != null ?
                new ObjectParameter("sSigla_Destino", sSigla_Destino) :
                new ObjectParameter("sSigla_Destino", typeof(string));
    
            var sCod_CargoDestinoParameter = sCod_CargoDestino != null ?
                new ObjectParameter("sCod_CargoDestino", sCod_CargoDestino) :
                new ObjectParameter("sCod_CargoDestino", typeof(string));
    
            var sCargo_EfectoParameter = sCargo_Efecto != null ?
                new ObjectParameter("sCargo_Efecto", sCargo_Efecto) :
                new ObjectParameter("sCargo_Efecto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SIGMA_spTotales_Efecto_Obtener_Result>("SIGMA_spTotales_Efecto_Obtener_FX", sNNEParameter, sSigla_DestinoParameter, sCod_CargoDestinoParameter, sCargo_EfectoParameter);
        }
    
        public virtual ObjectResult<SIGMA_spValorizacion_Detallada_Obtener_Result> SIGMA_spValorizacion_Detallada_Obtener_FX(string sNNE, string sNroLote, string sSigla)
        {
            var sNNEParameter = sNNE != null ?
                new ObjectParameter("sNNE", sNNE) :
                new ObjectParameter("sNNE", typeof(string));
    
            var sNroLoteParameter = sNroLote != null ?
                new ObjectParameter("sNroLote", sNroLote) :
                new ObjectParameter("sNroLote", typeof(string));
    
            var sSiglaParameter = sSigla != null ?
                new ObjectParameter("sSigla", sSigla) :
                new ObjectParameter("sSigla", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SIGMA_spValorizacion_Detallada_Obtener_Result>("SIGMA_spValorizacion_Detallada_Obtener_FX", sNNEParameter, sNroLoteParameter, sSiglaParameter);
        }
    }
}
