//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICI_MVC.Models
{
    using System;
    
    public partial class Pelicula
    {
        public string Titulo { get; set; }
        public int Duracion { get; set; }
        public int Año { get; set; }
        public string Genero { get; set; }
        public string Cod_Pais { get; set; }
        public string Des_Pais { get; set; }
        public Nullable<System.DateTime> Fecha_Estreno { get; set; }
    }
}
